version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: christophwurst/nextcloud
    versions:
    - "> 15.0"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - korelstar
